// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chatbuf-proto.proto

package id.ac.ui.clab.dchronochat;

public final class ChatbufProto {
  private ChatbufProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:id.ac.ui.clab.dchronochat.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string to = 1;</code>
     */
    boolean hasTo();
    /**
     * <code>required string to = 1;</code>
     */
    java.lang.String getTo();
    /**
     * <code>required string to = 1;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>required string from = 2;</code>
     */
    boolean hasFrom();
    /**
     * <code>required string from = 2;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>required string from = 2;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    boolean hasType();
    /**
     * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType getType();

    /**
     * <code>optional string data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 4;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 4;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>required int64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <code>required int64 sequence = 6;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int64 sequence = 6;</code>
     */
    long getSequence();
  }
  /**
   * Protobuf type {@code id.ac.ui.clab.dchronochat.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:id.ac.ui.clab.dchronochat.ChatMessage)
      ChatMessageOrBuilder {
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatMessage defaultInstance;
    public static ChatMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ChatMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              to_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              from_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType value = id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              data_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sequence_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return id.ac.ui.clab.dchronochat.ChatbufProto.internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return id.ac.ui.clab.dchronochat.ChatbufProto.internal_static_id_ac_ui_clab_dchronochat_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.class, id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatMessage> PARSER =
        new com.google.protobuf.AbstractParser<ChatMessage>() {
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType}
     */
    public enum ChatMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHAT = 0;</code>
       */
      CHAT(0, 0),
      /**
       * <code>HELLO = 1;</code>
       */
      HELLO(1, 1),
      /**
       * <code>LEAVE = 2;</code>
       */
      LEAVE(2, 2),
      /**
       * <code>JOIN = 3;</code>
       */
      JOIN(3, 3),
      /**
       * <code>OTHER = 4;</code>
       */
      OTHER(4, 4),
      ;

      /**
       * <code>CHAT = 0;</code>
       */
      public static final int CHAT_VALUE = 0;
      /**
       * <code>HELLO = 1;</code>
       */
      public static final int HELLO_VALUE = 1;
      /**
       * <code>LEAVE = 2;</code>
       */
      public static final int LEAVE_VALUE = 2;
      /**
       * <code>JOIN = 3;</code>
       */
      public static final int JOIN_VALUE = 3;
      /**
       * <code>OTHER = 4;</code>
       */
      public static final int OTHER_VALUE = 4;


      public final int getNumber() { return value; }

      public static ChatMessageType valueOf(int value) {
        switch (value) {
          case 0: return CHAT;
          case 1: return HELLO;
          case 2: return LEAVE;
          case 3: return JOIN;
          case 4: return OTHER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChatMessageType>() {
              public ChatMessageType findValueByNumber(int number) {
                return ChatMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChatMessageType[] VALUES = values();

      public static ChatMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ChatMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType)
    }

    private int bitField0_;
    public static final int TO_FIELD_NUMBER = 1;
    private java.lang.Object to_;
    /**
     * <code>required string to = 1;</code>
     */
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string to = 1;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          to_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string to = 1;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    /**
     * <code>required string from = 2;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string from = 2;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string from = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType type_;
    /**
     * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
     */
    public id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string data = 4;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 6;
    private long sequence_;
    /**
     * <code>required int64 sequence = 6;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 sequence = 6;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    private void initFields() {
      to_ = "";
      from_ = "";
      type_ = id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
      data_ = "";
      timestamp_ = 0L;
      sequence_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, sequence_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sequence_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code id.ac.ui.clab.dchronochat.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:id.ac.ui.clab.dchronochat.ChatMessage)
        id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return id.ac.ui.clab.dchronochat.ChatbufProto.internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return id.ac.ui.clab.dchronochat.ChatbufProto.internal_static_id_ac_ui_clab_dchronochat_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.class, id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.Builder.class);
      }

      // Construct using id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return id.ac.ui.clab.dchronochat.ChatbufProto.internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor;
      }

      public id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage getDefaultInstanceForType() {
        return id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.getDefaultInstance();
      }

      public id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage build() {
        id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage buildPartial() {
        id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage result = new id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sequence_ = sequence_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage) {
          return mergeFrom((id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage other) {
        if (other == id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.getDefaultInstance()) return this;
        if (other.hasTo()) {
          bitField0_ |= 0x00000001;
          to_ = other.to_;
          onChanged();
        }
        if (other.hasFrom()) {
          bitField0_ |= 0x00000002;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000008;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTo()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasSequence()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object to_ = "";
      /**
       * <code>required string to = 1;</code>
       */
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string to = 1;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            to_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string to = 1;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>required string to = 1;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <code>required string from = 2;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string from = 2;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            from_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string from = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>required string from = 2;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }

      private id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType type_ = id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
      /**
       * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType getType() {
        return type_;
      }
      /**
       * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public Builder setType(id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .id.ac.ui.clab.dchronochat.ChatMessage.ChatMessageType type = 3 [default = CHAT];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = id.ac.ui.clab.dchronochat.ChatbufProto.ChatMessage.ChatMessageType.CHAT;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>required int64 sequence = 6;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 sequence = 6;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>required int64 sequence = 6;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000020;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sequence = 6;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:id.ac.ui.clab.dchronochat.ChatMessage)
    }

    static {
      defaultInstance = new ChatMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:id.ac.ui.clab.dchronochat.ChatMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_id_ac_ui_clab_dchronochat_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023chatbuf-proto.proto\022\031id.ac.ui.clab.dch" +
      "ronochat\"\356\001\n\013ChatMessage\022\n\n\002to\030\001 \002(\t\022\014\n\004" +
      "from\030\002 \002(\t\022J\n\004type\030\003 \002(\01626.id.ac.ui.clab" +
      ".dchronochat.ChatMessage.ChatMessageType" +
      ":\004CHAT\022\014\n\004data\030\004 \001(\t\022\021\n\ttimestamp\030\005 \002(\003\022" +
      "\020\n\010sequence\030\006 \002(\003\"F\n\017ChatMessageType\022\010\n\004" +
      "CHAT\020\000\022\t\n\005HELLO\020\001\022\t\n\005LEAVE\020\002\022\010\n\004JOIN\020\003\022\t" +
      "\n\005OTHER\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_id_ac_ui_clab_dchronochat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_id_ac_ui_clab_dchronochat_ChatMessage_descriptor,
        new java.lang.String[] { "To", "From", "Type", "Data", "Timestamp", "Sequence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
